// <auto-generated />
using System;
using EMR.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMR.Infrastructure.Migrations.HisDemo
{
    [DbContext(typeof(HisDemoDbContext))]
    partial class HisDemoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMR.Domain.Entities.His.BenhNhan", b =>
                {
                    b.Property<string>("Ma")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte?>("GioiTinh")
                        .HasColumnType("tinyint");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Ma");

                    b.ToTable("BenhNhan", (string)null);
                });

            modelBuilder.Entity("EMR.Domain.Entities.His.LanKham", b =>
                {
                    b.Property<string>("Ma")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChanDoanRaVien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KhoaDieuTri")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaBenhNhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayRaVien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoVien")
                        .HasColumnType("datetime2");

                    b.HasKey("Ma");

                    b.HasIndex("MaBenhNhan");

                    b.ToTable("LanKham", (string)null);
                });

            modelBuilder.Entity("EMR.Domain.Entities.His.LanKham", b =>
                {
                    b.HasOne("EMR.Domain.Entities.His.BenhNhan", "BenhNhan")
                        .WithMany("LanKhams")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("EMR.Domain.Entities.His.BenhNhan", b =>
                {
                    b.Navigation("LanKhams");
                });
#pragma warning restore 612, 618
        }
    }
}
