// <auto-generated />
using System;
using EMR.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMR.Infrastructure.Migrations.Emr
{
    [DbContext(typeof(EmrDbContext))]
    [Migration("20260508064837_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMR.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorTen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Chitiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DoiTuongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoaiDoiTuong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("ThoiGian")
                        .IsDescending();

                    b.HasIndex("DoiTuongId", "HanhDong");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("EMR.Domain.Entities.ChuKy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CertNotAfter")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CertNotBefore")
                        .HasColumnType("datetime2");

                    b.Property<string>("CertSubject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DuongDanFileSau")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte>("LoaiCa")
                        .HasColumnType("tinyint");

                    b.Property<string>("LyDoLoi")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("NgayHoanTat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayYeuCau")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NguoiKyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sha256TruocKy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SignatureValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmartCa_CertId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SmartCa_SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SmartCa_TranCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SmartCa_TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TaiLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimestampSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.Property<string>("VaiTroKy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WebhookPayloadRaw")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiKyId");

                    b.HasIndex("SmartCa_TransactionId")
                        .IsUnique()
                        .HasFilter("[SmartCa_TransactionId] IS NOT NULL");

                    b.HasIndex("TaiLieuId");

                    b.HasIndex("TrangThai");

                    b.ToTable("ChuKy", (string)null);
                });

            modelBuilder.Entity("EMR.Domain.Entities.HoSoBenhAn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BacSiTaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("GioiTinh")
                        .HasColumnType("tinyint");

                    b.Property<string>("HoTenBenhNhan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("KhoLuuTru")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("KhoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaBenhNhanHIS")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaHoSo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaLanKhamHIS")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("BacSiTaoId");

                    b.HasIndex("MaBenhNhanHIS");

                    b.HasIndex("MaHoSo")
                        .IsUnique();

                    b.HasIndex("NgayTao");

                    b.HasIndex("KhoaId", "TrangThai");

                    b.ToTable("HoSoBenhAn", (string)null);
                });

            modelBuilder.Entity("EMR.Domain.Entities.Khoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KhoaChaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Nhom")
                        .HasColumnType("tinyint");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaChaId");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("Khoa", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b4cc343-8361-c219-e74c-b7d550c1e61c"),
                            Ma = "BGD",
                            Nhom = (byte)0,
                            Ten = "Ban Giám đốc",
                            ThuTu = 1
                        },
                        new
                        {
                            Id = new Guid("3e004de5-8106-c976-5116-1b483e1883aa"),
                            Ma = "P_TCHC",
                            Nhom = (byte)1,
                            Ten = "Phòng Tổ chức Hành chính",
                            ThuTu = 10
                        },
                        new
                        {
                            Id = new Guid("c8aac6ef-d8ad-1568-1145-1855e012efbe"),
                            Ma = "P_KHNV",
                            Nhom = (byte)1,
                            Ten = "Phòng Kế hoạch Nghiệp vụ",
                            ThuTu = 11
                        },
                        new
                        {
                            Id = new Guid("c24ed824-3c6a-efbd-d2d2-73b6df7f6e29"),
                            Ma = "P_TCKT",
                            Nhom = (byte)1,
                            Ten = "Phòng Tài chính kế toán",
                            ThuTu = 12
                        },
                        new
                        {
                            Id = new Guid("c8a5acb4-0376-87d9-17e1-55a7bb60497f"),
                            Ma = "P_DD",
                            Nhom = (byte)1,
                            Ten = "Phòng Điều dưỡng",
                            ThuTu = 13
                        },
                        new
                        {
                            Id = new Guid("70ae4769-9041-a4d8-f32a-6d7be3c79bf3"),
                            Ma = "P_TCCB",
                            Nhom = (byte)1,
                            Ten = "Phòng Tổ chức cán bộ",
                            ThuTu = 14
                        },
                        new
                        {
                            Id = new Guid("daad9986-718b-b74e-e130-a4a7b47c603d"),
                            Ma = "P_DS",
                            Nhom = (byte)1,
                            Ten = "Phòng Dân số",
                            ThuTu = 15
                        },
                        new
                        {
                            Id = new Guid("896f4c73-8760-e97f-d3f4-8860274c530e"),
                            Ma = "P_TC",
                            Nhom = (byte)1,
                            Ten = "Phòng Tiêm chủng",
                            ThuTu = 16
                        },
                        new
                        {
                            Id = new Guid("26b92fd3-497c-1ced-92cd-f7f6224c779f"),
                            Ma = "P_KSBT",
                            Nhom = (byte)1,
                            Ten = "Phòng Khám KSBT",
                            ThuTu = 17
                        },
                        new
                        {
                            Id = new Guid("23e8b814-4ea7-95c1-ead4-5816cad0305f"),
                            Ma = "K_NGOAI",
                            Nhom = (byte)2,
                            Ten = "Khoa Ngoại",
                            ThuTu = 20
                        },
                        new
                        {
                            Id = new Guid("e6bed160-d5cb-d526-fa2a-d6be730d9183"),
                            Ma = "K_NOI",
                            Nhom = (byte)2,
                            Ten = "Khoa Nội",
                            ThuTu = 21
                        },
                        new
                        {
                            Id = new Guid("1f759b61-e86c-aaa8-62d8-7aff4e85e726"),
                            Ma = "K_COVID",
                            Nhom = (byte)2,
                            Ten = "Khoa Điều trị COVID-19",
                            ThuTu = 22
                        },
                        new
                        {
                            Id = new Guid("b44544bf-dc24-1efa-1c6b-3c5af9548611"),
                            Ma = "K_SAN",
                            Nhom = (byte)2,
                            Ten = "Khoa Sản",
                            ThuTu = 23
                        },
                        new
                        {
                            Id = new Guid("c75ef115-a297-a18e-feb3-e59c439d0865"),
                            Ma = "K_NHI",
                            Nhom = (byte)2,
                            Ten = "Khoa Nhi",
                            ThuTu = 24
                        },
                        new
                        {
                            Id = new Guid("95bd14d9-3244-d67f-ccd5-07eabe1b4790"),
                            Ma = "K_LCK",
                            Nhom = (byte)2,
                            Ten = "Khoa Liên Chuyên Khoa",
                            ThuTu = 25
                        },
                        new
                        {
                            Id = new Guid("98df8e63-89da-bcfb-6a45-8554f7693fa8"),
                            Ma = "K_YHCT",
                            Nhom = (byte)2,
                            Ten = "Khoa YHCT - VLTL&PHCN",
                            ThuTu = 26
                        },
                        new
                        {
                            Id = new Guid("12fc9f46-a4d8-4e05-fae7-8e326462bbd5"),
                            Ma = "K_HSCC",
                            Nhom = (byte)2,
                            Ten = "Khoa Hồi sức Cấp cứu",
                            ThuTu = 27
                        },
                        new
                        {
                            Id = new Guid("9dcb52dd-4679-99e7-2e80-14ff1168df41"),
                            Ma = "K_CDHA",
                            Nhom = (byte)2,
                            Ten = "Khoa Chẩn đoán Hình ảnh",
                            ThuTu = 28
                        },
                        new
                        {
                            Id = new Guid("a4c8df16-b15f-6552-b491-ff256b2982ee"),
                            Ma = "K_XN",
                            Nhom = (byte)2,
                            Ten = "Khoa Xét nghiệm",
                            ThuTu = 29
                        },
                        new
                        {
                            Id = new Guid("83bcb35b-4eb0-3fc1-025e-72b0afec0224"),
                            Ma = "K_DUOC",
                            Nhom = (byte)2,
                            Ten = "Khoa Dược-TTB-VTYT",
                            ThuTu = 30
                        },
                        new
                        {
                            Id = new Guid("cec3bea9-c3e5-6d3d-e1c1-ce8a73d1870c"),
                            Ma = "K_KSBT",
                            Nhom = (byte)2,
                            Ten = "Khoa Kiểm soát bệnh tật và HIV/AIDS",
                            ThuTu = 31
                        },
                        new
                        {
                            Id = new Guid("7bbb8bff-8be8-3761-b7de-0f21ab3109f4"),
                            Ma = "K_YTCC",
                            Nhom = (byte)2,
                            Ten = "Khoa YTCC - DD & ATTP",
                            ThuTu = 32
                        },
                        new
                        {
                            Id = new Guid("0ab26272-8a7f-280f-b020-a7b625f449fb"),
                            Ma = "K_KSNK",
                            Nhom = (byte)2,
                            Ten = "Khoa Kiểm soát nhiễm khuẩn",
                            ThuTu = 33
                        },
                        new
                        {
                            Id = new Guid("d82cb7fd-7d2b-e2c3-2e47-a8fe69c6c761"),
                            Ma = "K_PK",
                            Nhom = (byte)2,
                            Ten = "Khoa Phòng khám",
                            ThuTu = 34
                        },
                        new
                        {
                            Id = new Guid("06322610-66ac-d888-a31e-46ebf704710c"),
                            KhoaChaId = new Guid("95bd14d9-3244-d67f-ccd5-07eabe1b4790"),
                            Ma = "K_LCK_NTRU_RHM",
                            Nhom = (byte)2,
                            Ten = "Liên Chuyên Khoa (Ngoại trú RHM)",
                            ThuTu = 35
                        },
                        new
                        {
                            Id = new Guid("97cbbdd3-b484-0f24-b6d0-0af8bc6a53c6"),
                            KhoaChaId = new Guid("98df8e63-89da-bcfb-6a45-8554f7693fa8"),
                            Ma = "K_YHCT_NTRU",
                            Nhom = (byte)2,
                            Ten = "Khoa YHCT - VLTL&PHCN (Ngoại trú)",
                            ThuTu = 36
                        },
                        new
                        {
                            Id = new Guid("2f3a2d7e-64f5-99e3-0391-25ff75e33c15"),
                            Ma = "TYT_HKB",
                            Nhom = (byte)3,
                            Ten = "TYT Hòa Khánh Bắc",
                            ThuTu = 50
                        },
                        new
                        {
                            Id = new Guid("7e5c20b5-3662-5d7f-03ee-0a45982596f9"),
                            Ma = "TYT_HKN",
                            Nhom = (byte)3,
                            Ten = "TYT Hòa Khánh Nam",
                            ThuTu = 51
                        },
                        new
                        {
                            Id = new Guid("24875405-ea4e-5840-dd0a-a0e7514ab909"),
                            Ma = "TYT_HHB",
                            Nhom = (byte)3,
                            Ten = "TYT Hòa Hiệp Bắc",
                            ThuTu = 52
                        },
                        new
                        {
                            Id = new Guid("ff999ac1-4c27-bb9b-a17e-c08ddb74718c"),
                            Ma = "TYT_HHN",
                            Nhom = (byte)3,
                            Ten = "TYT Hòa Hiệp Nam",
                            ThuTu = 53
                        },
                        new
                        {
                            Id = new Guid("3bc299d3-2aee-db12-1e36-49c93da36c2c"),
                            Ma = "TYT_HM",
                            Nhom = (byte)3,
                            Ten = "TYT Hòa Minh",
                            ThuTu = 54
                        },
                        new
                        {
                            Id = new Guid("a2aa8c07-8476-7977-f349-13d58988027b"),
                            Ma = "TYT_HV",
                            Nhom = (byte)3,
                            Ten = "Trạm y tế phường Hải Vân",
                            ThuTu = 55
                        },
                        new
                        {
                            Id = new Guid("f4a6f47f-8ca6-035a-842e-4f844d97363f"),
                            Ma = "TYT_KHAC",
                            Nhom = (byte)3,
                            Ten = "Trạm Y tế (chung)",
                            ThuTu = 56
                        });
                });

            modelBuilder.Entity("EMR.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("KhoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CCCD")
                        .IsUnique()
                        .HasFilter("[CCCD] IS NOT NULL");

                    b.HasIndex("KhoaId");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("EMR.Domain.Entities.NguoiDungVaiTro", b =>
                {
                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VaiTroId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NguoiDungId", "VaiTroId");

                    b.HasIndex("VaiTroId");

                    b.ToTable("NguoiDung_VaiTro", (string)null);
                });

            modelBuilder.Entity("EMR.Domain.Entities.TaiLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DuongDanLuuTru")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("HoSoBenhAnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("KichThuoc")
                        .HasColumnType("bigint");

                    b.Property<string>("LoaiTaiLieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayUpload")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NguoiUploadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("TrangThaiKy")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("HoSoBenhAnId");

                    b.HasIndex("NguoiUploadId");

                    b.HasIndex("TrangThaiKy");

                    b.ToTable("TaiLieu", (string)null);
                });

            modelBuilder.Entity("EMR.Domain.Entities.VaiTro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("825aa01d-a9a0-a07c-f1a8-dee376cd78d7"),
                            Ma = "BACSI",
                            MoTa = "Tạo hồ sơ, ký bệnh án mình tạo",
                            Ten = "Bác sĩ"
                        },
                        new
                        {
                            Id = new Guid("36da78af-74ea-8d49-9ff0-79ec250c85bb"),
                            Ma = "DIEUDUONG",
                            MoTa = "Hỗ trợ tạo/cập nhật hồ sơ, ký phiếu chăm sóc",
                            Ten = "Điều dưỡng"
                        },
                        new
                        {
                            Id = new Guid("1f981080-1288-4c68-59fb-ed608719577f"),
                            Ma = "DUOCSI",
                            MoTa = "Quản lý đơn thuốc, ký xác nhận cấp phát",
                            Ten = "Dược sĩ"
                        },
                        new
                        {
                            Id = new Guid("e53c79aa-6512-780d-4cbc-8ea1fa150965"),
                            Ma = "TRUONGKHOA",
                            MoTa = "Ký duyệt cấp khoa, xem hồ sơ trong khoa",
                            Ten = "Trưởng khoa"
                        },
                        new
                        {
                            Id = new Guid("c547e799-29b3-5c4b-174e-b4fd5eae7bef"),
                            Ma = "KHTH",
                            MoTa = "Kiểm tra hồ sơ, chuyển kho BV, báo cáo",
                            Ten = "Kế hoạch nghiệp vụ"
                        },
                        new
                        {
                            Id = new Guid("7e9fc296-6444-b732-407d-7e9b586bafd5"),
                            Ma = "LANHDAO_BV",
                            MoTa = "Ký duyệt cấp BV, xem toàn bộ",
                            Ten = "Lãnh đạo Bệnh viện"
                        },
                        new
                        {
                            Id = new Guid("468e54da-69b6-9c75-7064-a25e947e8c0c"),
                            Ma = "ADMIN",
                            MoTa = "Quản lý người dùng, vai trò, audit",
                            Ten = "Quản trị hệ thống"
                        },
                        new
                        {
                            Id = new Guid("ae81ac86-aac8-dd25-ff2f-9a1ed7cf6d86"),
                            Ma = "BENHNHAN",
                            MoTa = "Đăng nhập app, xem hồ sơ của mình",
                            Ten = "Bệnh nhân"
                        });
                });

            modelBuilder.Entity("EMR.Domain.Entities.ChuKy", b =>
                {
                    b.HasOne("EMR.Domain.Entities.NguoiDung", "NguoiKy")
                        .WithMany()
                        .HasForeignKey("NguoiKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMR.Domain.Entities.TaiLieu", "TaiLieu")
                        .WithMany("ChuKys")
                        .HasForeignKey("TaiLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiKy");

                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("EMR.Domain.Entities.HoSoBenhAn", b =>
                {
                    b.HasOne("EMR.Domain.Entities.NguoiDung", "BacSiTao")
                        .WithMany()
                        .HasForeignKey("BacSiTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMR.Domain.Entities.Khoa", "Khoa")
                        .WithMany("HoSoBenhAns")
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSiTao");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("EMR.Domain.Entities.Khoa", b =>
                {
                    b.HasOne("EMR.Domain.Entities.Khoa", "KhoaCha")
                        .WithMany("KhoaCons")
                        .HasForeignKey("KhoaChaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("KhoaCha");
                });

            modelBuilder.Entity("EMR.Domain.Entities.NguoiDung", b =>
                {
                    b.HasOne("EMR.Domain.Entities.Khoa", "Khoa")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("EMR.Domain.Entities.NguoiDungVaiTro", b =>
                {
                    b.HasOne("EMR.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("VaiTros")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMR.Domain.Entities.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("EMR.Domain.Entities.TaiLieu", b =>
                {
                    b.HasOne("EMR.Domain.Entities.HoSoBenhAn", "HoSoBenhAn")
                        .WithMany("TaiLieus")
                        .HasForeignKey("HoSoBenhAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMR.Domain.Entities.NguoiDung", "NguoiUpload")
                        .WithMany()
                        .HasForeignKey("NguoiUploadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoSoBenhAn");

                    b.Navigation("NguoiUpload");
                });

            modelBuilder.Entity("EMR.Domain.Entities.HoSoBenhAn", b =>
                {
                    b.Navigation("TaiLieus");
                });

            modelBuilder.Entity("EMR.Domain.Entities.Khoa", b =>
                {
                    b.Navigation("HoSoBenhAns");

                    b.Navigation("KhoaCons");

                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("EMR.Domain.Entities.NguoiDung", b =>
                {
                    b.Navigation("VaiTros");
                });

            modelBuilder.Entity("EMR.Domain.Entities.TaiLieu", b =>
                {
                    b.Navigation("ChuKys");
                });

            modelBuilder.Entity("EMR.Domain.Entities.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
